Bekri/Bekri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bekri/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
]

Bekri/core/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('contact/', views.contact, name = "contact"),
    path('terms/', views.terms, name="terms"),
    path('signup/', views.signup, name = "signup"),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form = LoginForm), name= "login"),
]

Bekri/dashboard/urls.py
from django.urls import path
from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

Bekri/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('', views.browse, name='browse'),
]

Bekri/core/models.py
from django.db import models

# Create your models here.

Bekri/core/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your username', 'class': 'w-full py-4 px-4 rounded-xl' }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder':'Your email address', 'class': 'w-full py-4 px-4 rounded-xl' }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'create a strong password', 'class': 'w-full py-4 px-4 rounded-xl' }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Repeat password', 'class': 'w-full py-4 px-4 rounded-xl' }))
    

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your username', 'class': 'w-full py-4 px-4 rounded-xl' }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'enter password', 'class': 'w-full py-4 px-4 rounded-xl' }))
    

Bekri/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Items
from .forms import SignupForm
# Create your views here.
def index(request):
    items = Items.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html',{ 'categories':categories,'items': items,})

def contact(request):
    return render(request,'core/contact.html')

def terms(request):
    return render(request, "core/terms.html")
def signup(request):
    if request.method =='POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    else: 
        form = SignupForm()
    
    return render(request, 'core/signup.html', {'form':form})

Bekri/core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset = "utf-8">
        <meta name="viewpoint" content="width=device-width, initial-scale=1.0">

        <script src = "https://cdn.tailwindcss.com"></script>

        <title>{% block title%}{% endblock %} | Spash</title>
    </head>

    <body >
        
        <nav class="py-6 px-6 flex justify-between items-center border-b border-yellow-50 bg-blue-100">
            <section class="title">
            <a href = "/" class = "text-4xl font-bold ">Splash</a>
            </section>
            <div class = "space-x-6 ">
                <a href="{%url 'item:new' %}" class= "text-lg font-semibold hover:text-sky-200">Add Item</a>
                <a href="{% url 'item:browse'%}" class= "text-lg font-semibold hover:text-sky-200">Browse</a>
                
                
                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700">Inbox</a>
                        <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700">Dashboard</a>
                        <a href="{% url 'core:login'%}" class="px-6 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700">Logout</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700">Sign up</a>
                {% endif %}
                
        </nav>
        <div class="px-6 py-6 color: bg-white">
           
            {% block content %} {% endblock %}
        </div>
        <footer class = "py-10 px-6 mt-20 flex justify-between bg-blue-100">
            <div class = "w-2/3 pr-10">
                <h3 class = "mb-5 font-bold text-blue-900">About</h3>
                <p class="text-lg text-blue-800">An arts ecommerce store with all art supplies imaginable! Art is the way to communicate with the human soul to convey meaningful ideas. We're here to help support you on your journey to get the right supplies!</p>
            </div>

            <div class="w-1/3">
                <h3 class = "mb-5 font-semibold text-blue-900">Menu</h3> 

                <ul class="space-y-6">
                    <li><a href = "{% url 'core:terms' %}" class="text-blue-500 hover:text-white">Terms and Conditions</a></li>
                    <li><a href = "{% url 'core:contact' %}" class="text-blue-500 hover:text-white">Contact</a></li>
                    
                    
                </ul>
            
            </div>
        </footer>
    </body>
</html>

Bekri/core/templates/core/contact.html
{% extends 'core/base.html' %}


{% block title %}Contact{% endblock %}

{% block content%}
<h1 class= "mb-12 text-2xl text-center font-bold">Contact us!</h1>
<p class="font-semibold">Call us at: 111-222-3333</p>
<p class="font-semibold">Email us at: generic-mail.com</p>
{% endblock %}

Bekri/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock %}

{% block content%}
<div class="mt-6 px-6 py-12 rounded-xl bg-blue-100 rounded-xl">
    <h2 class = "mb-12 text-2xl text-center font-bold">Newest Items</h2>
    
    <div class = "grid grid-cols-3 gap-3"> 
        {% for item in items %}
            <div>
                <a class = "font-semibold text-blue-900" href = "{% url 'item:detail' item.id%}">
                    <div>
                        <img src = "{{ item.image.url }}" class="rounded-t-xl">
                    </div>
                    
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-700">Price: ${{item.price}}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

Bekri/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-4 bg-blue-100 rounded-xl">
    <h1 class="mb-6 text-3xl font-bold text-blue-900">Log in</h1>

    <form method="POST" action =".">
        {% csrf_token %}
        

        <div class = "mb-3 ">
            <label class="inline-block mb-2 font-semibold">Username</label><br>
            {{form.username}}
        </div>
      
        <div class = "mb-3">
            <label class="inline-block mb-2 font-semibold">Password</label><br>
            {{form.password}}
            
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-white rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg text-white bg-yellow-400 hover:bg-yellow-100 rounded-xl font-semibold">Login</button>
        <a class=" py-4 hover:text-white font-semibold text-color-" href ="{% url 'core:signup'%}">New Here? Sign up!</a>    
    </form>

</div>
{% endblock %}

Bekri/core/templates/core/signup.html
{% extends 'core/base.html' %}



{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-4 bg-blue-100 rounded-xl">
    <h1 class="mb-6 text-3xl font-semibold ">Sign up</h1>

    <form method="POST" action =".">
        {% csrf_token %}
        

        <div class = "mb-3">
            <label class="inline-block mb-2 font-semibold">Username</label><br>
            {{form.username}}
        </div>
        <div class = "mb-3">
            <label class="inline-block mb-2 font-semibold">Email</label><br>
            {{form.email}}
        </div>
        <div class = "mb-3">
            <label class="inline-block mb-2 font-semibold">Password</label><br>
            {{form.password1}}
            
            <div class = "mb-3">
                <label class="inline-block mb-2 font-semibold">Repeat Password</label><br>
                {{form.password2}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-gray-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-yellow-400 hover:bg-yellow-700 text-white rounded-xl font-semibold">Submit</button>    
    </form>

</div>
{% endblock %}

Bekri/core/templates/core/terms.html
{% extends 'core/base.html' %}

{% block title %}Terms and Conditions{% endblock %}

{% block content%}
<h1 class="font-bold text-2xl text-center">Terms and Conditions of Service</h1>
<br>
<p class= "font-semibold">(NOTE: NOT REAL TERMS AND SERVICE) By accessing this website, you are agreeing to be bound by these website Terms and Conditions of Service, the Privacy Policy, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. We may modify these Terms and Conditions at any time without notice to you by posting revised Terms and Conditions of Service. Your use of the website constitutes your binding acceptance of these Terms and Conditions of Service, including any modifications that we make. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.
    The Service includes a combination of content that we create and that other third party content suppliers create. You understand that the Service are provided "AS IS", and that Copyandpasteemoji.com does not guarantee the accuracy, integrity or quality of any content available on the website. Copyandpasteemoji.com disclaims all responsibility and liability for the accuracy, availability, timeliness, security or reliability of the Service. We reserve the right to modify, suspend or discontinue the Service with or without notice at any time and without any liability to you.
    The Service is directed to adults and is not directed to children under the age of 18. You must be 18 years of age or older to use the Service. <br><br>
    
    Access to Sites<br>
    Copyandpasteemoji.com grants you a limited license to access and use the website via Web browsers or RSS readers only. You agree not to copy, republish, frame, download, transmit, modify, rent, lease, loan, sell, assign, distribute, license, sublicense, reverse engineer, or create derivative works based on the Content or Design of the website.
    In addition, you agree not to use any data mining, robots, or similar data gathering and extraction methods in connection with the website. You further agree that you will not interfere with another member's use and enjoyment of the Service; you will not interfere with or disrupt the security measures of the Service; you will not interfere with or disrupt networks connected to the Service.<br>
    
    Use License<br>
    Permission is granted to temporarily download one copy of the materials (information or software) on Copyandpasteemoji.com website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
    - modify or copy the materials;
    - use the materials for any commercial purpose, or for any public display (commercial or non-commercial);
    - attempt to decompile or reverse engineer any software contained on Copyandpasteemoji.com website;
    - remove any copyright or other proprietary notations from the materials; or
    - transfer the materials to another person or "mirror" the materials on any other server;
    - transfer the materials to another person or "mirror" the materials on any other server;
    - access the site using automated means which may degrade service for others.
    This license shall automatically terminate if you violate any of these restrictions and may be terminated by Copyandpasteemoji.com at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
    
    Conduct on Website and Contribution of Content
    Your use of the Website is subject to all applicable laws and regulations, and you are solely responsible for the substance of your communications through the Website. By posting information in or otherwise using any communications service that may be available to you on or through this Website, you agree that you will not upload, share, post, or otherwise distribute or facilitate distribution of any content (including text, communications, data or other information) that:
    
    - is known by you to be false, inaccurate or misleading;
    
    - is for purposes of spamming;
    
    - is unlawful, obscene, vulgar, shocking, excessive profanity, threatens or advocates for harm on oneself or others, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another's privacy, tortious, contains explicit or graphic descriptions or accounts of sexual acts (including but not limited to sexual language of a violent or threatening nature directed at another individual or group of individuals), pornographic, adult or mature, or otherwise violates our rules or policies, profane or indecent including any communication that constitutes (or encourages conduct that would constitute) a criminal offense, gives rise to civil liability or otherwise violates any local, state or federal law, bullies, victimizes, harasses, degrades, or intimidates an individual or group of individuals;
    
    - is malware, adware, hacking, cracking content, Illicit drugs and drug paraphernalia content, or any other content that is illegal, promotes illegal activity or infringes on the legal rights of others;
    
    - contains links to software viruses or any other computer code, files, or programs itself that are designed or intended to disrupt, damage, or limit the functioning of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any data or other information of any third party;
    
    - impersonates any person or entity, including any of our employees or representatives;
    
    - is regarding programs which compensate users for clicking ads or offers, performing searches, surfing websites or reading emails;
    
    - claims the identity, characteristics or qualifications of another person;
    
    - for which you were compensated or granted any consideration by any third party;
    
    - incites hatred against, promotes discrimination of, or disparages an individual or group on the basis of their race or ethnic origin, religion, disability, age, nationality, veteran status, sexual orientation, gender, gender identity, or other characteristic that is associated with systemic discrimination or marginalization;
    
    - infringes or violates on any patent, trademark, trade secret, copyright, right of publicity, other proprietary right of any party, or other intellectual property rights;
    
    - promotes, sells, or advertises tobacco or tobacco-related products, alcoholic beverages, prescription drugs, weapons or ammunition (e.g., firearms, firearm components, fighting knives, stun guns), distribution of coursework or student essays, products obtained from endangered or threatened species;
    
    - constitutes unauthorized or unsolicited advertising, junk or bulk email (also known as "spamming"), chain letters, any other form of unauthorized solicitation, or any form of lottery or gambling.
    
    We neither endorse nor assume any liability for the contents of any material uploaded or submitted by third party users of the Website. However, we and our agents have the right at their sole discretion to remove any content that, in our judgment, does not comply with our Terms and Conditions of Service, Adsense program policies, and any other rules of user conduct for our Website, or is otherwise harmful, objectionable, or inaccurate.
    
    In addition, you may not use the Service to breach security or attempt to gain unauthorized access to another network or server. Users who violate systems or network security may incur criminal or civil liability. Not all areas of the Website may be available to you or other authorized users of the Website.
    
    Much of the content of this Website is provided by and is the responsibility of the person or people who made those postings. We do not ensure the accuracy or legitimacy of any comments, remarks or other information posted or generated by users of this Website and, therefore, take no responsibility for such content provided by users or other third parties. However, we reserve the right to delete any content at any time without notifying the person from which such content originated. You hereby consent to such removal and waive any claim against us arising out of such removal of content. We are not responsible for any failure or delay in removing content.
    
    Any failure by us to enforce or exercise any provision of these Terms and Conditions of Service or related rights shall not constitute a waiver of that right or provision.
    
    Use of Materials and Proprietary Rights
    Content displayed on or through the Service is protected by copyright as a collective work and/or compilation. Any reproduction or redistribution of the site or the collective work is prohibited without the express written consent of Copyandpasteemoji.com.
    By posting Content to any public area of the Service, you automatically grant, and you represent and warrant that you have the right to grant, to Copyandpasteemoji.com an irrevocable, perpetual, non-exclusive, fully paid, worldwide license to use, copy, perform, display, and distribute said Content and to prepare derivative works of, or incorporate into other works, said Content, and to grant and authorize sublicenses of the foregoing.
    Subject to our Privacy Policy, any communication or material that you transmit to this site or to us, whether by electronic mail, post, or other means, for any reason, will be treated as non-confidential and non-proprietary.
    Please do not submit confidential or proprietary information to us unless we have mutually agreed in writing otherwise. We are also unable to accept your unsolicited ideas or proposals, so please do not submit them to us in any circumstance.
    By posting your content using the website, you are granting an unrestricted, irrevocable, non-exclusive, royalty-free, perpetual, worldwide, and fully transferable, assignable, and sublicensable right and license to use, copy, reproduce, modify, adapt, publish, translate, create collective or derivative works from, distribute, perform and display your content in whole or in part and to incorporate it in other works in any form, media, or technology now known or later developed. You further warrant that all so-called moral rights in the content have been waived.
    By posting content to the website, you warrant and represent that you either own or otherwise control all of the rights to that content, including, without limitation, all the rights necessary for you to provide, post, upload, input or submit the content, or that your use of the content is a protected fair use. You agree that you will not knowingly provide material and misleading false information. You represent and warrant also that the content you supply does not violate these Terms. It is your sole responsibility to ensure that your postings do not disclose confidential and/or proprietary information, including personal financial information, information covered by a nondisclosure agreement, and information that you are not authorized to disclose. We caution you not to disclose personal information about yourself or your children, such as social security numbers, credit card numbers, etc.
    You agree to indemnify and hold Us and Our affiliated companies, and their directors, officers and employees, harmless for any and all claims or demands, including reasonable attorney fees, that arise from or otherwise relate to your use of the website, any content you supply to the website, or your violation of these Terms or the rights of another.
    
    Security and Password
    You are solely responsible for maintaining the confidentiality of your password and account and for any and all statements made and acts or omissions that occur through the use of your password and account. Therefore, you must take steps to ensure that others do not gain access to your password and account. Our personnel will never ask you for your password. You may not transfer or share your account with anyone, and we reserve the right to immediately terminate your account if you do transfer or share your account.
    You agree to be responsible for any action that occurs as the result of any access to your account as the result of access with your password. You agree that if it is determine that your password has been compromised that your account may be closed or access to the account may be terminated with no obligation to keep or maintain the information or data in your account.
    
    Termination of Use
    You agree that we may, in our sole discretion, terminate or suspend your access to all or part of the site with or without notice and for any reason, including, without limitation, breach of these Terms of Use. Any suspected fraudulent, abusive or illegal activity may be grounds for terminating your relationship and may be referred to appropriate law enforcement authorities.
    Upon termination or suspension, regardless of the reasons therefore, your right to use the services available on this site immediately ceases, and you acknowledge and agree that we may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or this site. We shall not be liable to you or any third party for any claims or damages arising out of any termination or suspension or any other actions taken by us in connection with such termination or suspension.</p>
{% endblock %}